# Generated by Django 4.1 on 2024-03-23 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Serviceapp', '0009_alter_serviceregistration_rate'),
        ('Guestapp', '0006_remove_servicereg_categoryid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('bookingid', models.AutoField(primary_key=True, serialize=False)),
                ('bookingdate', models.DateField(auto_now_add=True)),
                ('eventdate', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('customerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guestapp.customerreg')),
                ('providerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guestapp.servicereg')),
                ('serviceid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Serviceapp.serviceregistration')),
            ],
        ),
    ]
