# Generated by Django 4.1 on 2024-02-26 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0002_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('locationid', models.AutoField(primary_key=True, serialize=False)),
                ('locationname', models.CharField(max_length=50)),
                ('districtid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Adminapp.district')),
            ],
        ),
    ]
