# Generated by Django 4.1 on 2024-03-20 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0004_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subategory',
            fields=[
                ('subcatid', models.AutoField(primary_key=True, serialize=False)),
                ('subcatname', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('desc', models.CharField(max_length=50)),
                ('categoryid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Adminapp.category')),
            ],
        ),
    ]
