# Generated by Django 4.1 on 2024-03-20 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0005_subategory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subategory',
            new_name='Subcategory',
        ),
    ]
