# Generated by Django 4.1 on 2024-03-20 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0006_rename_subategory_subcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='image',
            new_name='subimage',
        ),
    ]
