# Generated by Django 4.1 on 2024-03-15 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guestapp', '0004_delete_travelreg'),
        ('Adminapp', '0004_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travelreg',
            fields=[
                ('vehicleid', models.AutoField(primary_key=True, serialize=False)),
                ('vname', models.CharField(max_length=50)),
                ('seat', models.BigIntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('desc', models.CharField(max_length=50)),
                ('rate', models.BigIntegerField()),
                ('categoryid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Adminapp.category')),
                ('locationid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Adminapp.location')),
                ('providerid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Guestapp.servicereg')),
            ],
        ),
    ]
