# Generated by Django 4.1 on 2024-03-19 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guestapp', '0004_delete_travelreg'),
        ('Adminapp', '0004_category'),
        ('Serviceapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cateringhreg',
            fields=[
                ('caterid', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('item', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('desc', models.CharField(max_length=50)),
                ('rate', models.BigIntegerField()),
                ('categoryid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Adminapp.category')),
                ('locationid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Adminapp.location')),
                ('providerid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Guestapp.servicereg')),
            ],
        ),
    ]
