# Generated by Django 4.1 on 2024-03-21 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0007_rename_image_subcategory_subimage'),
        ('Serviceapp', '0006_remove_destinationreg_categoryid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinationreg',
            name='subcatid',
        ),
        migrations.RemoveField(
            model_name='serviceregistration',
            name='categoryid',
        ),
        migrations.AddField(
            model_name='destinationreg',
            name='categoryid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Adminapp.category'),
        ),
        migrations.AddField(
            model_name='serviceregistration',
            name='subcatid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Adminapp.subcategory'),
        ),
    ]
