# Generated by Django 4.1 on 2024-03-22 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Serviceapp', '0007_remove_destinationreg_subcatid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceregistration',
            name='rate',
            field=models.BigIntegerField(null=True),
        ),
    ]
