# Generated by Django 4.1 on 2024-03-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Serviceapp', '0008_serviceregistration_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceregistration',
            name='rate',
            field=models.BigIntegerField(default=1111),
            preserve_default=False,
        ),
    ]
