# Generated by Django 4.1 on 2024-03-12 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0004_category'),
        ('Guestapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicereg',
            fields=[
                ('providerid', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.BigIntegerField()),
                ('servicename', models.CharField(max_length=50)),
                ('regdate', models.DateField(auto_now_add=True)),
                ('categoryid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Adminapp.category')),
                ('locationid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Adminapp.location')),
                ('loginid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Guestapp.login')),
            ],
        ),
    ]
