# Generated by Django 4.1 on 2024-03-15 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guestapp', '0003_travelreg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Travelreg',
        ),
    ]
