# Generated by Django 4.1 on 2024-03-21 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0007_rename_image_subcategory_subimage'),
        ('Guestapp', '0004_delete_travelreg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customerreg',
            fields=[
                ('customerid', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50)),
                ('mname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('addr', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('regdate', models.DateField(auto_now_add=True)),
                ('locationid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Adminapp.location')),
                ('loginid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Guestapp.login')),
            ],
        ),
    ]
