# Generated by Django 4.1 on 2024-03-22 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guestapp', '0005_customerreg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicereg',
            name='categoryid',
        ),
    ]
